path_classifiers:
  test:
    - "*.c"
extraction:
  cpp:
    after_prepare:
      - pip3 install meson==0.59.2
      - export PATH="/opt/work/.local/bin:$PATH"
    configure:
      command:
        - /opt/work/.local/bin/meson setup builddir/
    index:
      build_command:
        - /opt/work/.local/bin/meson compile -C builddir/
  python:
    python_setup:
      version: 3
